# This file is similar to blue-deployment.yaml but defines a "green" version of the Deployment:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-green
  labels:
    app: flask-app
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
      version: green
  template:
    metadata:
      labels:
        app: flask-app
        version: green
    spec:
      containers:
      - name: flask-container
        image: hirusha2000/coinbase-crypto-exchnage
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: production